apps/exams/urls.py
from django.urls import path
from . import views

app_name = 'exams'

urlpatterns = [
    path('', views.list_exams, name='list_exams'),
    path('adicionar/', views.add_exam, name='add_exam'),
    path('editar/<int:id_exam>/', views.edit_exam, name='edit_exam'),
    path('excluir/<int:id_exam>/', views.delete_exam, name='delete_exam'),
]

examesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medicos/', include('medics.urls', namespace='medics')),
    path('pacientes/', include('pacients.urls', namespace='pacients')),
    path('agendamentos/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/exams/models.py
from django.db import models
from schedules.models import Schedule
from pacients.models import Pacient

# Create your models here.

class Exam(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    date = models.DateField('Data de Realizacao')
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    pacient = models.ForeignKey(Pacient, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Exame'
        verbose_name_plural = 'Exames'
        ordering =['id']

    def __str__(self):
        return self.schedule

apps/exams/forms.py
from django import forms
from .models import Exam

class ExamForm(forms.ModelForm):

    class Meta:
        model = Exam
        exclude = ('created_on' , 'updated_on',)

apps/exams/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import ExamForm
from .models import Exam

# Create your views here.

def add_exam(request):
    template_name = 'exams/add_exam.html'
    context = {}
    if request.method == 'POST':
        form = ExamForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('exams:list_exams')
    form = ExamForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_exams(request):
    template_name = 'exams/list_exams.html'
    exams = Exam.objects.filter()
    context = {
        'exams': exams
    }
    return render(request, template_name, context)

def edit_exam(request, id_exam):
    template_name = 'exams/add_exam.html'
    context ={}
    exam = get_object_or_404(Exam, id=id_exam)
    if request.method == 'POST':
        form = ExamForm(request.POST, request.FILES,  instance=exam)
        if form.is_valid():
            form.save()
            return redirect('exams:list_exams')
    form = ExamForm(instance=exam)
    context['form'] = form
    return render(request, template_name, context)

def delete_exam(request, id_exam):
    exam = Exam.objects.get(id=id_exam)
    exam.delete()
    return redirect('exams:list_exams')

templates/exams/add_exam.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Exame - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Exame</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.schedule.id_for_label }}">Talao</label>
                    {{ form.schedule|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.date.id_for_label }}">Data de Realizacao</label>
                    {{ form.date|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.pacient.id_for_label }}">Paciente</label>
                    {{ form.pacient|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control" }}
                </div>
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/exams/list_exams.html
{% extends 'base.html' %}

{% block title %}

    Resultados de Exames - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Resultados de Exames</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'exams:add_exam' %}">Registrar Resultado de Exame</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Talao</th>
                    <th scope="col">Data de Realizacao</th>
                    <th scope="col">Paciente</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for exam in exams %}
                        <tr>
                            <th scope="row">{{ exam.id }}</th>
                            <td>{{ exam.schedule }}</td>
                            <td>{{ exam.date }}</td>
                            <td>{{ exam.pacient }}</td>
                            <td>{{ exam.status }}</td>
                            <td>
                                <a href="{% url 'exams:edit_exam' exam.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'exams:delete_exam' exam.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}