apps/medics/urls.py
from django.urls import path
from . import views

app_name = 'medics'

urlpatterns = [
    path('', views.list_medics, name='list_medics'),
    path('adicionar/', views.add_medic, name='add_medic'),
    path('editar/<int:id_medic>', views.edit_medic, name='edit_medic'),
    path('excluir/<int:id_medic>', views.delete_medic, name='delete_medic'),
]

examesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medicos/', include('medics.urls', namespace='medics')),
    path('pacientes/', include('pacients.urls', namespace='pacients')),
    path('agendamentos/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/medics/models.py
from django.db import models

# Create your models here.

class Medic(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=200)
    crm = models.CharField('CRM', max_length=10)
    spec = models.CharField('Especialidade', max_length=100)
    address = models.CharField('Endereco', max_length=100)
    phone = models.CharField('Telefone', max_length=20)
    
    class Meta:
        verbose_name = 'Medico'
        verbose_name_plural = 'Medicos'
        ordering =['id']

    def __str__(self):
        return self.name

apps/medics/forms.py
from django import forms
from .models import Medic

class MedicForm(forms.ModelForm):
    
    class Meta:
        model = Medic
        exclude = ('created_on', 'updated_on',)

apps/medics/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import MedicForm
from .models import Medic

# Create your views here.

def add_medic(request):
    template_name = 'medics/add_medic.html'
    context = {}
    if request.method == 'POST':
        form = MedicForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('medics:list_medics')
    form = MedicForm
    context['form'] = form
    return render(request, template_name, context)

def list_medics(request):
    template_name = 'medics/list_medics.html'
    medics = Medic.objects.filter()
    context = {
        'medics': medics
    }
    return render(request, template_name, context)

def edit_medic(request, id_medic):
    template_name = 'medics/add_medic.html'
    context = {}
    medic = get_object_or_404(Medic, id=id_medic)
    if request.method == 'POST':
        form = MedicForm(request.POST, instance=medic)
        if form.is_valid():
            form.save()
            return redirect('medics:list_medics')
    form = MedicForm(instance=medic)
    context['form'] = form
    return render(request, template_name, context)

def delete_medic(request, id_medic):
    medic = Medic.objects.get(id=id_medic)
    medic.delete()
    return redirect('medics:list_medics')

templates/medics/add_medic.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Medico - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Medico</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">CRM</label>
                    {{ form.crm|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Especialidade</label>
                    {{ form.spec|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Telefone</label>
                    {{ form.phone|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/medics/list_medics.html
{% extends 'base.html' %}

{% block title %}

    Lista de Medicos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Medicos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'medics:add_medic' %}">Cadastro de novo medico</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CRM</th>
                    <th scope="col">Especialidade</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Telefone</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for medic in medics %}
                        <tr>
                            <th scope="row">{{ medic.id }}</th>
                            <td>{{ medic.name }}</td>
                            <td>{{ medic.crm }}</td>
                            <td>{{ medic.spec }}</td>
                            <td>{{ medic.address }}</td>
                            <td>{{ medic.phone }}</td>
                            <td>
                                <a href="{% url 'medics:edit_medic' medic.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'medics:delete_medic' medic.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}