apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

apps/exams/urls.py
from django.urls import path
from . import views

app_name = 'exams'

urlpatterns = [
    path('', views.list_exams, name='list_exams'),
    path('adicionar/', views.add_exam, name='add_exam'),
    path('editar/<int:id_exam>/', views.edit_exam, name='edit_exam'),
    path('excluir/<int:id_exam>/', views.delete_exam, name='delete_exam'),
]

apps/medics/urls.py
from django.urls import path
from . import views

app_name = 'medics'

urlpatterns = [
    path('', views.list_medics, name='list_medics'),
    path('adicionar/', views.add_medic, name='add_medic'),
    path('editar/<int:id_medic>', views.edit_medic, name='edit_medic'),
    path('excluir/<int:id_medic>', views.delete_medic, name='delete_medic'),
]

apps/pacients/urls.py
from django.urls import path
from . import views

app_name = 'pacients'

urlpatterns = [
    path('', views.list_pacients, name='list_pacients'),
    path('adicionar/', views.add_pacient, name='add_pacient'),
    path('editar/<int:id_pacient>', views.edit_pacient, name='edit_pacient'),
    path('excluir/<int:id_pacient>', views.delete_pacient, name='delete_pacient'),
]

examesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medicos/', include('medics.urls', namespace='medics')),
    path('pacientes/', include('pacients.urls', namespace='pacients')),
    path('agendamentos/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Gerenciamento de Exames Médicos{% endblock title %}</title>
</head>
<body>

    <!-- INICIO: Bloco do Bootstrap a ser incluido -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Gerenciamento de Exames Médicos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'schedules:list_schedules' %}">Agendamento de Exames</a>
                        <a class="dropdown-item" href="{% url 'exams:list_exams' %}">Resultado de Exames</a>
                        <a class="dropdown-item" href="{% url 'medics:list_medics' %}">Médicos</a>
                        <a class="dropdown-item" href="{% url 'pacients:list_pacients' %}">Pacientes</a>  
                    </div>
                </li>
            </ul>
            <form action="#" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown05">
                            <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                            <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                            <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                        </div>
                    </li>
                </ul>
        </div>
        {% endif %}
    </nav>
    <!-- FIM: Bloco do Bootstrap a ser incluido -->


    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>