apps/pacients/urls.py
from django.urls import path
from . import views

app_name = 'pacients'

urlpatterns = [
    path('', views.list_pacients, name='list_pacients'),
    path('adicionar/', views.add_pacient, name='add_pacient'),
    path('editar/<int:id_pacient>', views.edit_pacient, name='edit_pacient'),
    path('excluir/<int:id_pacient>', views.delete_pacient, name='delete_pacient'),
]

examesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medicos/', include('medics.urls', namespace='medics')),
    path('pacientes/', include('pacients.urls', namespace='pacients')),
    path('agendamentos/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pacients/models.py
from django.db import models

# Create your models here.

class Pacient(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=200)
    cpf = models.CharField('CPF', max_length=10)
    bdate = models.CharField('Data de Nascimento', max_length=50)
    address = models.CharField('Endereco', max_length=100)
    phone = models.CharField('Telefone', max_length=20)
    
    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering =['id']

    def __str__(self):
        return self.name

apps/pacients/forms.py
from django import forms
from .models import Pacient

class PacientForm(forms.ModelForm):
    
    class Meta:
        model = Pacient
        exclude = ('created_on', 'updated_on',)

apps/pacients/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import PacientForm
from .models import Pacient

# Create your views here.

def add_pacient(request):
    template_name = 'pacients/add_pacient.html'
    context = {}
    if request.method == 'POST':
        form = PacientForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('pacients:list_pacients')
    form = PacientForm
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_pacients(request):
    template_name = 'pacients/list_pacients.html'
    pacients = Pacient.objects.filter()
    context = {
        'pacients': pacients
    }
    return render(request, template_name, context)

def edit_pacient(request, id_pacient):
    template_name = 'pacients/add_pacient.html'
    context = {}
    pacient = get_object_or_404(Pacient, id=id_pacient)
    if request.method == 'POST':
        form = PacientForm(request.POST, instance=pacient)
        if form.is_valid():
            form.save()
            return redirect('pacients:list_pacients')
    form = PacientForm(instance=pacient)
    context['form'] = form
    return render(request, template_name, context)

def delete_pacient(request, id_pacient):
    pacient = Pacient.objects.get(id=id_pacient)
    pacient.delete()
    return redirect('pacients:list_pacients')

templates/pacients/add_pacient.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Paciente - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Paciente</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.cpf.id_for_label }}">CPF</label>
                    {{ form.cpf|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.bdate.id_for_label }}">Data de Nascimento</label>
                    {{ form.bdate|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.phone.id_for_label }}">Telefone</label>
                    {{ form.phone|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/pacients/list_pacients.html
{% extends 'base.html' %}

{% block title %}

    Lista de Pacientes - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Pacientes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'pacients:add_pacient' %}">Cadastro de novo paciente</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Telefone</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for pacient in pacients %}
                        <tr>
                            <th scope="row">{{ pacient.id }}</th>
                            <td>{{ pacient.name }}</td>
                            <td>{{ pacient.cpf }}</td>
                            <td>{{ pacient.bdate }}</td>
                            <td>{{ pacient.address }}</td>
                            <td>{{ pacient.phone }}</td>
                            <td>
                                <a href="{% url 'pacients:edit_pacient' pacient.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'pacients:delete_pacient' pacient.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}